name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'Homeworks/06 Настройка CI/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  # Приводим название репозитория к нижнему регистру для Docker
  IMAGE_NAME: kseniyakotrikova/asp.net

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # Указываем контекст. Если Dockerfile в корне: .
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
